title: <p align="center"> Vipin Jaguri </p>
logo: /assets/img/My.jpeg

description:
  <p align="center">
  <a href="https://github.com/VipinJaguri">GitHub</a>
  
  <br>   
  I'm  currently working in a defense PSU on VoIP, SIP, Embedded Systems and HDL.
  Working on projects with IAF for last 5 years. 
  <br>
  </p>
